// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/FeatureGraphic.tsx": () => import("../components/mockups/FeatureGraphic.tsx"),
  "./components/mockups/ShotCart.tsx": () => import("../components/mockups/ShotCart.tsx"),
  "./components/mockups/ShotCategories.tsx": () => import("../components/mockups/ShotCategories.tsx"),
  "./components/mockups/ShotCheckout.tsx": () => import("../components/mockups/ShotCheckout.tsx"),
  "./components/mockups/ShotHome.tsx": () => import("../components/mockups/ShotHome.tsx"),
  "./components/mockups/ShotOffers.tsx": () => import("../components/mockups/ShotOffers.tsx"),
  "./components/mockups/ShotProduct.tsx": () => import("../components/mockups/ShotProduct.tsx")
};
